/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dolgozat;

import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author WeimperGergőZsombor(
 */
public class PizzaRendelo extends javax.swing.JFrame {
public double osszeg = 0;
public double segedOsszeg = 0;
    /**
     * Creates new form PizzaRendelo
     */
    public PizzaRendelo() {
        initComponents();
        //int osszeg = 0;
        //int segedOsszeg = 0;
        fgv_osszeg(osszeg, segedOsszeg);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_teszta_meret = new javax.swing.ButtonGroup();
        btnG_pizza_meret = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        pnl_kep = new javax.swing.JPanel();
        lbl_kep = new javax.swing.JLabel();
        lbl_pizza_cim = new javax.swing.JLabel();
        pnl_teszta = new javax.swing.JPanel();
        rbt_vekony = new javax.swing.JRadioButton();
        rbt_vastag = new javax.swing.JRadioButton();
        rbt_kozepes = new javax.swing.JRadioButton();
        pnl_meret = new javax.swing.JPanel();
        rbt_32cm = new javax.swing.JRadioButton();
        rbt_52cm = new javax.swing.JRadioButton();
        rbt_26cm = new javax.swing.JRadioButton();
        pnl_elerhetoseg = new javax.swing.JPanel();
        lbl_nev = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_telefon = new javax.swing.JLabel();
        txf_nev = new javax.swing.JTextField();
        txf_email = new javax.swing.JTextField();
        txf_telefon = new javax.swing.JTextField();
        cmb_pizzafajta = new javax.swing.JComboBox<>();
        lbl_txt_pizzafajta = new javax.swing.JLabel();
        pnl_feltet = new javax.swing.JPanel();
        cbx_kukorica = new javax.swing.JCheckBox();
        cbx_bacon = new javax.swing.JCheckBox();
        cbx_bbq = new javax.swing.JCheckBox();
        cbx_paradicsom = new javax.swing.JCheckBox();
        cbx_bab = new javax.swing.JCheckBox();
        cbx_gomba = new javax.swing.JCheckBox();
        cbx_oliva = new javax.swing.JCheckBox();
        cbx_paprika = new javax.swing.JCheckBox();
        pnl_osszegzes = new javax.swing.JPanel();
        lbl_txt_Osszeg = new javax.swing.JLabel();
        lbl_osszeg = new javax.swing.JLabel();
        pnl_rendeles_kilepes = new javax.swing.JPanel();
        lbl_txt_mennyiseg = new javax.swing.JLabel();
        spnr_mennyiseg = new javax.swing.JSpinner();
        btn_rendeles = new javax.swing.JButton();
        btn_kilepes = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzéria - étlap");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(540, 540));

        pnl_kep.setBackground(new java.awt.Color(255, 255, 255));
        pnl_kep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_kep.setBackground(new java.awt.Color(255, 255, 255));
        lbl_kep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/pizza1.png"))); // NOI18N

        javax.swing.GroupLayout pnl_kepLayout = new javax.swing.GroupLayout(pnl_kep);
        pnl_kep.setLayout(pnl_kepLayout);
        pnl_kepLayout.setHorizontalGroup(
            pnl_kepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_kep)
        );
        pnl_kepLayout.setVerticalGroup(
            pnl_kepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kepLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_kep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbl_pizza_cim.setBackground(new java.awt.Color(204, 204, 204));
        lbl_pizza_cim.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbl_pizza_cim.setText("<html>\n<p style=\"color: #a1723b\">Pizza rendelés</p>\n</html>");

        pnl_teszta.setBackground(new java.awt.Color(204, 204, 204));
        pnl_teszta.setBorder(javax.swing.BorderFactory.createTitledBorder("Tészta"));

        btnG_teszta_meret.add(rbt_vekony);
        rbt_vekony.setText("Vékony");

        btnG_teszta_meret.add(rbt_vastag);
        rbt_vastag.setText("Vastag");

        btnG_teszta_meret.add(rbt_kozepes);
        rbt_kozepes.setText("Közepes");

        javax.swing.GroupLayout pnl_tesztaLayout = new javax.swing.GroupLayout(pnl_teszta);
        pnl_teszta.setLayout(pnl_tesztaLayout);
        pnl_tesztaLayout.setHorizontalGroup(
            pnl_tesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tesztaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rbt_vekony)
                .addGap(18, 18, 18)
                .addComponent(rbt_kozepes)
                .addGap(18, 18, 18)
                .addComponent(rbt_vastag)
                .addGap(14, 14, 14))
        );
        pnl_tesztaLayout.setVerticalGroup(
            pnl_tesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tesztaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_vekony)
                    .addComponent(rbt_vastag)
                    .addComponent(rbt_kozepes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_meret.setBackground(new java.awt.Color(204, 204, 204));
        pnl_meret.setBorder(javax.swing.BorderFactory.createTitledBorder("Méret"));

        btnG_pizza_meret.add(rbt_32cm);
        rbt_32cm.setText("32 cm");
        rbt_32cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_32cmActionPerformed(evt);
            }
        });

        btnG_pizza_meret.add(rbt_52cm);
        rbt_52cm.setText("52 cm");
        rbt_52cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_52cmActionPerformed(evt);
            }
        });

        btnG_pizza_meret.add(rbt_26cm);
        rbt_26cm.setText("26 cm");
        rbt_26cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_26cmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_meretLayout = new javax.swing.GroupLayout(pnl_meret);
        pnl_meret.setLayout(pnl_meretLayout);
        pnl_meretLayout.setHorizontalGroup(
            pnl_meretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_meretLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rbt_26cm)
                .addGap(18, 18, 18)
                .addComponent(rbt_32cm)
                .addGap(18, 18, 18)
                .addComponent(rbt_52cm)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnl_meretLayout.setVerticalGroup(
            pnl_meretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_meretLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_meretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_32cm)
                    .addComponent(rbt_52cm)
                    .addComponent(rbt_26cm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_elerhetoseg.setBackground(new java.awt.Color(204, 204, 204));
        pnl_elerhetoseg.setBorder(javax.swing.BorderFactory.createTitledBorder("Elérhetőség:"));

        lbl_nev.setText("Név:");

        lbl_email.setText("E-mail:");

        lbl_telefon.setText("Tel.:");

        javax.swing.GroupLayout pnl_elerhetosegLayout = new javax.swing.GroupLayout(pnl_elerhetoseg);
        pnl_elerhetoseg.setLayout(pnl_elerhetosegLayout);
        pnl_elerhetosegLayout.setHorizontalGroup(
            pnl_elerhetosegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_elerhetosegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_elerhetosegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_telefon)
                    .addComponent(lbl_email)
                    .addComponent(lbl_nev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_elerhetosegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txf_nev)
                    .addComponent(txf_telefon)
                    .addComponent(txf_email))
                .addContainerGap())
        );
        pnl_elerhetosegLayout.setVerticalGroup(
            pnl_elerhetosegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_elerhetosegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_elerhetosegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nev)
                    .addComponent(txf_nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnl_elerhetosegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnl_elerhetosegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefon)
                    .addComponent(txf_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmb_pizzafajta.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cmb_pizzafajta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz...", "Sajtos ", "Sonka kukorica", "Szalámis", "4 sajtos", "Roston csirkés" }));
        cmb_pizzafajta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_pizzafajtaItemStateChanged(evt);
            }
        });
        cmb_pizzafajta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pizzafajtaActionPerformed(evt);
            }
        });

        lbl_txt_pizzafajta.setText("Pizza fajta:");

        pnl_feltet.setBorder(javax.swing.BorderFactory.createTitledBorder("Extra feltét (+200 Ft / db)"));

        cbx_kukorica.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_kukorica.setText("Kukorica");
        cbx_kukorica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paprikaActionPerformed(evt);
            }
        });

        cbx_bacon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_bacon.setText("Bacon");
        cbx_bacon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_baconItemStateChanged(evt);
            }
        });
        cbx_bacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_baconActionPerformed(evt);
            }
        });

        cbx_bbq.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_bbq.setText("BBQ");
        cbx_bbq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paprikaActionPerformed(evt);
                cbx_bbqActionPerformed(evt);
            }
        });

        cbx_paradicsom.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_paradicsom.setText("Paradicsom");
        cbx_paradicsom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paprikaActionPerformed(evt);
            }
        });

        cbx_bab.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_bab.setText("Bab");
        cbx_bab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paprikaActionPerformed(evt);
            }
        });

        cbx_gomba.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_gomba.setText("Gomba");
        cbx_gomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paprikaActionPerformed(evt);
            }
        });

        cbx_oliva.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_oliva.setText("Oliva");
        cbx_oliva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paprikaActionPerformed(evt);
            }
        });

        cbx_paprika.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbx_paprika.setText("Paprika");
        cbx_paprika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_paprikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_feltetLayout = new javax.swing.GroupLayout(pnl_feltet);
        pnl_feltet.setLayout(pnl_feltetLayout);
        pnl_feltetLayout.setHorizontalGroup(
            pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_feltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_kukorica)
                    .addComponent(cbx_paradicsom)
                    .addComponent(cbx_bab)
                    .addComponent(cbx_paprika))
                .addGap(21, 21, 21)
                .addGroup(pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_bacon)
                    .addComponent(cbx_bbq)
                    .addComponent(cbx_gomba)
                    .addComponent(cbx_oliva))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_feltetLayout.setVerticalGroup(
            pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_feltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_kukorica)
                    .addComponent(cbx_bacon))
                .addGap(18, 18, 18)
                .addGroup(pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_bbq)
                    .addComponent(cbx_paradicsom))
                .addGap(18, 18, 18)
                .addGroup(pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_bab)
                    .addComponent(cbx_gomba))
                .addGap(18, 18, 18)
                .addGroup(pnl_feltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_oliva)
                    .addComponent(cbx_paprika))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_osszegzes.setBackground(new java.awt.Color(204, 204, 204));
        pnl_osszegzes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_txt_Osszeg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_txt_Osszeg.setForeground(new java.awt.Color(51, 51, 51));
        lbl_txt_Osszeg.setText("Összeg: ");

        lbl_osszeg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_osszeg.setForeground(new java.awt.Color(0, 153, 0));
        lbl_osszeg.setText("0");

        javax.swing.GroupLayout pnl_osszegzesLayout = new javax.swing.GroupLayout(pnl_osszegzes);
        pnl_osszegzes.setLayout(pnl_osszegzesLayout);
        pnl_osszegzesLayout.setHorizontalGroup(
            pnl_osszegzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_osszegzesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_txt_Osszeg)
                .addGap(18, 18, 18)
                .addComponent(lbl_osszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnl_osszegzesLayout.setVerticalGroup(
            pnl_osszegzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_osszegzesLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnl_osszegzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_txt_Osszeg)
                    .addComponent(lbl_osszeg))
                .addGap(19, 19, 19))
        );

        pnl_rendeles_kilepes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_txt_mennyiseg.setText("Mennyiség:");

        spnr_mennyiseg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        btn_rendeles.setText("<html> <p style=\"color:#187516 \">Rendelés</p> </html>");
        btn_rendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rendelesActionPerformed(evt);
            }
        });

        btn_kilepes.setForeground(new java.awt.Color(153, 0, 0));
        btn_kilepes.setText("Kilépés");
        btn_kilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kilepesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_rendeles_kilepesLayout = new javax.swing.GroupLayout(pnl_rendeles_kilepes);
        pnl_rendeles_kilepes.setLayout(pnl_rendeles_kilepesLayout);
        pnl_rendeles_kilepesLayout.setHorizontalGroup(
            pnl_rendeles_kilepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_rendeles_kilepesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btn_rendeles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_kilepes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_rendeles_kilepesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_txt_mennyiseg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnr_mennyiseg)
                .addContainerGap())
        );
        pnl_rendeles_kilepesLayout.setVerticalGroup(
            pnl_rendeles_kilepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_rendeles_kilepesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_rendeles_kilepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnr_mennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_txt_mennyiseg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_rendeles_kilepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_kilepes)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_rendeles_kilepesLayout.createSequentialGroup()
                        .addComponent(btn_rendeles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_txt_pizzafajta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_pizzafajta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7))
                            .addComponent(pnl_elerhetoseg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_teszta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_meret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_osszegzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lbl_pizza_cim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_kep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_feltet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_rendeles_kilepes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnl_meret, pnl_osszegzes, pnl_teszta});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_kep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(pnl_feltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_rendeles_kilepes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_pizza_cim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_elerhetoseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_pizzafajta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_txt_pizzafajta))
                        .addGap(18, 18, 18)
                        .addComponent(pnl_teszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_meret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_osszegzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnl_meret, pnl_teszta});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt_26cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_26cmActionPerformed
        /*osszeg = Double.parseDouble(lbl_osszeg.getText()) * 0.85;
        fgv_szorzasOsszeg(osszeg, segedOsszeg);
        //lbl_osszeg.setText(String.valueOf(osszeg));*/
        osszeg = Double.parseDouble(lbl_osszeg.getText());
        if(rbt_26cm.isSelected())
            segedOsszeg = 0.85;
        else if(rbt_32cm.isSelected())
            segedOsszeg = 1;
        else if(rbt_52cm.isSelected())
            segedOsszeg = 2.25;
        fgv_szorzasOsszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_rbt_26cmActionPerformed

    private void cmb_pizzafajtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pizzafajtaActionPerformed
        //System.out.println("Most fut le a kód"); - Teszteltem a működését
        Object pizzaIz = cmb_pizzafajta.getSelectedItem();
        
        double[] arak = new double[6];
        arak[0] = 0;
        arak[1] = 2000;
        arak[2] = 2200;
        arak[3] = 2200;
        arak[4] = 2100;
        arak[5] = 2300;
        
        int pIndex = cmb_pizzafajta.getSelectedIndex();
        
        if(pIndex == 0)
            JOptionPane.showMessageDialog(rootPane, "Nincs pizzafajta választva!");
        else if(pIndex == 1)
            segedOsszeg = arak[1];
        else if(pIndex == 2)
            segedOsszeg = arak[2];
        else if(pIndex == 3)
            segedOsszeg = arak[3];
        else if(pIndex == 4)
            segedOsszeg = arak[4];
        else if(pIndex == 5)
            segedOsszeg = arak[5];
        else if(pIndex == 6)
            segedOsszeg = arak[6];
        else
            System.out.println("Nem működik.");
        
        fgv_osszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_cmb_pizzafajtaActionPerformed

    private void cbx_baconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_baconActionPerformed
        if(cbx_bacon.isSelected() == true)
            segedOsszeg = 200;
        else
            segedOsszeg = 0;
        fgv_osszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_cbx_baconActionPerformed

    private void rbt_32cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_32cmActionPerformed
        /*osszeg = Double.parseDouble(lbl_osszeg.getText()) * 1;
        fgv_szorzasOsszeg(osszeg, segedOsszeg);*/
        osszeg = Double.parseDouble(lbl_osszeg.getText());
        if(rbt_26cm.isSelected())
            segedOsszeg = 0.85;
        else if(rbt_32cm.isSelected())
            segedOsszeg = 1;
        else if(rbt_52cm.isSelected())
            segedOsszeg = 2.25;
        fgv_szorzasOsszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_rbt_32cmActionPerformed

    private void cmb_pizzafajtaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_pizzafajtaItemStateChanged
        /*Object[] pizzaIz = new Object[6];
        pizzaIz[0] = cmb_pizzafajta.getItemAt(0);
        pizzaIz[1] = cmb_pizzafajta.getItemAt(1);
        pizzaIz[2] = cmb_pizzafajta.getItemAt(2);
        pizzaIz[3] = cmb_pizzafajta.getItemAt(3);
        pizzaIz[4] = cmb_pizzafajta.getItemAt(4);
        pizzaIz[5] = cmb_pizzafajta.getItemAt(5);
        int hossz = cmb_pizzafajta.getItemCount();
        for (int i = 0; i < hossz; i++) {
            pizzaIz[i] = cmb_pizzafajta.getItemAt(i);
        }
        
        
        
        double[] arak = new double[6];
        arak[0] = 0;
        arak[1] = 2000;
        arak[2] = 2200;
        arak[3] = 2200;
        arak[4] = 2100;
        arak[5] = 2300;
        
        if(cmb_pizzafajta.equals(pizzaIz[0]))
            JOptionPane.showMessageDialog(rootPane, "Nincs pizzafajta választva!");
        else if(cmb_pizzafajta.equals(pizzaIz[1]))
            segedOsszeg = arak[1];
        else if(cmb_pizzafajta.equals(pizzaIz[2]))
            segedOsszeg = arak[2];
        else if(cmb_pizzafajta.equals(pizzaIz[3]))
            segedOsszeg = arak[3];
        else if(cmb_pizzafajta.equals(pizzaIz[4]))
            segedOsszeg = arak[4];
        else if(cmb_pizzafajta.equals(pizzaIz[5]))
            segedOsszeg = arak[5];
        else if(cmb_pizzafajta.equals(pizzaIz[6]))
            segedOsszeg = arak[6];
        else
            System.out.println("Nem működik.");
        
        
        segedOsszeg = 0;
        osszeg += segedOsszeg;

        lbl_osszeg.setText(String.valueOf(osszeg) + " Ft");
        */
        
        
    }//GEN-LAST:event_cmb_pizzafajtaItemStateChanged

    private void rbt_52cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_52cmActionPerformed
        /*segedOsszeg = 2.2;
        //osszeg = Double.parseDouble(lbl_osszeg.getText());
        fgv_szorzasOsszeg(osszeg, segedOsszeg);*/
        osszeg = Double.parseDouble(lbl_osszeg.getText());
        fgv_szorzasOsszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_rbt_52cmActionPerformed

    private void btn_kilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kilepesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_kilepesActionPerformed

    private void btn_rendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rendelesActionPerformed
        int pIndex = cmb_pizzafajta.getSelectedIndex();
        
        if(pIndex == 0)
            JOptionPane.showMessageDialog(rootPane, "Nincs pizzafajta választva!");
        else
            JOptionPane.showMessageDialog(rootPane, "Köszönjük a rendelését! 1 órán belül várható az étel.");
        
        if(pIndex != 0)
            System.exit(0);
            
    }//GEN-LAST:event_btn_rendelesActionPerformed

    private void cbx_paprikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_paprikaActionPerformed
        if(cbx_paprika.isSelected() == true)
            segedOsszeg = 200;
        else
            segedOsszeg = -200;
        fgv_osszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_cbx_paprikaActionPerformed

    private void cbx_bbqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_bbqActionPerformed
        if(cbx_bbq.isSelected() == true)
            segedOsszeg = 200;
        else
            segedOsszeg = 0;
        fgv_osszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_cbx_bbqActionPerformed

    private void cbx_baconItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_baconItemStateChanged
        if(cbx_bacon.isSelected() == true)
            segedOsszeg = 200;
        else
            segedOsszeg = -200;
        fgv_osszeg(osszeg, segedOsszeg);
    }//GEN-LAST:event_cbx_baconItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaRendelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_pizza_meret;
    private javax.swing.ButtonGroup btnG_teszta_meret;
    private javax.swing.JButton btn_kilepes;
    private javax.swing.JButton btn_rendeles;
    private javax.swing.JCheckBox cbx_bab;
    private javax.swing.JCheckBox cbx_bacon;
    private javax.swing.JCheckBox cbx_bbq;
    private javax.swing.JCheckBox cbx_gomba;
    private javax.swing.JCheckBox cbx_kukorica;
    private javax.swing.JCheckBox cbx_oliva;
    private javax.swing.JCheckBox cbx_paprika;
    private javax.swing.JCheckBox cbx_paradicsom;
    private javax.swing.JComboBox<String> cmb_pizzafajta;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_kep;
    private javax.swing.JLabel lbl_nev;
    private javax.swing.JLabel lbl_osszeg;
    private javax.swing.JLabel lbl_pizza_cim;
    private javax.swing.JLabel lbl_telefon;
    private javax.swing.JLabel lbl_txt_Osszeg;
    private javax.swing.JLabel lbl_txt_mennyiseg;
    private javax.swing.JLabel lbl_txt_pizzafajta;
    private javax.swing.JPanel pnl_elerhetoseg;
    private javax.swing.JPanel pnl_feltet;
    private javax.swing.JPanel pnl_kep;
    private javax.swing.JPanel pnl_meret;
    private javax.swing.JPanel pnl_osszegzes;
    private javax.swing.JPanel pnl_rendeles_kilepes;
    private javax.swing.JPanel pnl_teszta;
    private javax.swing.JRadioButton rbt_26cm;
    private javax.swing.JRadioButton rbt_32cm;
    private javax.swing.JRadioButton rbt_52cm;
    private javax.swing.JRadioButton rbt_kozepes;
    private javax.swing.JRadioButton rbt_vastag;
    private javax.swing.JRadioButton rbt_vekony;
    private javax.swing.JSpinner spnr_mennyiseg;
    private javax.swing.JTextField txf_email;
    private javax.swing.JTextField txf_nev;
    private javax.swing.JTextField txf_telefon;
    // End of variables declaration//GEN-END:variables

    private double fgv_osszeg(double osszeg, double segedOsszeg) {
        
        /*String strOsszeg = lbl_osszeg.getText();
        osszeg = Double.parseDouble(strOsszeg);*/
        //osszeg változó = Aktuális számmal

            osszeg = Double.parseDouble(lbl_osszeg.getText());
            osszeg += segedOsszeg;

        lbl_osszeg.setText(String.valueOf(osszeg));
        
        return osszeg;
    }
    
    private double fgv_szorzasOsszeg(double osszeg, double segedOsszeg) {
        osszeg = Double.parseDouble(lbl_osszeg.getText());
        //osszeg változó = Aktuális számmal
        //osszeg = osszeg * segedOsszeg;
        osszeg = osszeg * segedOsszeg;
        lbl_osszeg.setText(String.valueOf(osszeg));
        
        return osszeg;
    }
    
}
